"""Generated project-document sync for orchestration state."""

import os
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from datetime import UTC, datetime
from pathlib import Path

from dgentic.redaction import redact_sensitive_values
from dgentic.schemas import (
    OrchestrationBlocker,
    OrchestrationDocumentSyncResult,
    OrchestrationFollowUp,
    OrchestrationRun,
    PlanStatus,
)
from dgentic.settings import get_settings

PROGRESS_DOCUMENT_PATH = Path("docs/progress/orchestration-runs.md")
BACKLOG_DOCUMENT_PATH = Path("docs/planning/orchestration-follow-ups.md")


def sync_orchestration_documents(
    runs: list[OrchestrationRun] | Callable[[], list[OrchestrationRun]],
) -> OrchestrationDocumentSyncResult:
    root_dir = get_settings().root_dir.resolve()
    with _document_sync_lock(root_dir):
        run_snapshot = runs() if callable(runs) else runs
        sorted_runs = sorted(run_snapshot, key=lambda run: run.created_at, reverse=True)
        _write_generated_document(
            root_dir,
            PROGRESS_DOCUMENT_PATH,
            _progress_document(sorted_runs),
        )
        _write_generated_document(
            root_dir,
            BACKLOG_DOCUMENT_PATH,
            _backlog_document(sorted_runs),
        )

    return OrchestrationDocumentSyncResult(
        progress_path=PROGRESS_DOCUMENT_PATH.as_posix(),
        backlog_path=BACKLOG_DOCUMENT_PATH.as_posix(),
        run_count=len(sorted_runs),
        open_follow_up_count=sum(1 for _run, _follow_up in _open_follow_ups(sorted_runs)),
        unresolved_blocker_count=sum(
            1 for _run, _blocker in _unresolved_backlog_blockers(sorted_runs)
        ),
    )


def _safe_document_path(root_dir: Path, relative_path: Path) -> Path:
    if relative_path.is_absolute() or any(part in {"", ".", ".."} for part in relative_path.parts):
        raise ValueError("Generated orchestration document path must be relative and normalized.")
    path = root_dir / relative_path
    current = root_dir
    for part in relative_path.parts:
        current /= part
        if current.exists() and current.is_symlink():
            raise ValueError(
                f"Generated orchestration document path must not contain symlinks: {current}"
            )
    resolved_parent = path.parent.resolve()
    if root_dir != resolved_parent and root_dir not in resolved_parent.parents:
        raise ValueError("Generated orchestration document path must stay inside rootDir.")
    return path


@contextmanager
def _document_sync_lock(root_dir: Path) -> Iterator[None]:
    settings = get_settings()
    if settings.data_dir.is_absolute():
        lock_dir = settings.data_dir
    else:
        lock_dir = root_dir / settings.data_dir
    lock_dir.mkdir(parents=True, exist_ok=True)
    lock_path = lock_dir / "orchestration-documents.lock"
    with lock_path.open("a+b") as lock_file:
        if os.name == "nt":
            import msvcrt

            lock_file.seek(0)
            msvcrt.locking(lock_file.fileno(), msvcrt.LK_LOCK, 1)
            try:
                yield
            finally:
                lock_file.seek(0)
                msvcrt.locking(lock_file.fileno(), msvcrt.LK_UNLCK, 1)
        else:
            import fcntl

            fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
            try:
                yield
            finally:
                fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)


def _write_generated_document(root_dir: Path, relative_path: Path, content: str) -> None:
    path = _safe_document_path(root_dir, relative_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path = _safe_document_path(root_dir, relative_path)
    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%S%fZ")
    counter = 0
    while True:
        suffix = f"{timestamp}-{counter}" if counter else timestamp
        temp_path = path.with_name(f".{path.name}.tmp-{suffix}")
        try:
            with temp_path.open("x", encoding="utf-8") as temp_file:
                temp_file.write(content)
            break
        except FileExistsError:
            counter += 1
    temp_path.replace(path)


def _progress_document(runs: list[OrchestrationRun]) -> str:
    lines = [
        "# DGentic Orchestration Run Status",
        "",
        "Generated by DGentic from orchestration state. Manual edits may be replaced.",
        "",
    ]
    if not runs:
        lines.extend(["No orchestration runs recorded.", ""])
        return "\n".join(lines)

    for run in runs:
        lines.extend(
            [
                f"## {_text(run.id)}",
                "",
                f"- Objective: {_text(run.objective)}",
                f"- Status: `{run.status}`",
                f"- Created: `{run.created_at.isoformat()}`",
                f"- Updated: `{run.updated_at.isoformat()}`",
                f"- Requested by: {_text(run.requested_by or 'system')}",
                f"- Scheduled tasks: {_csv(run.scheduled_task_ids)}",
                "",
                "### Tasks",
                "",
            ]
        )
        for task in run.tasks:
            lines.append(
                f"- `{task.status}` `{_text(task.id)}` ({_text(task.role)}): {_text(task.title)}"
            )
        lines.extend(["", "### Blockers", ""])
        unresolved = [blocker for blocker in run.blockers if blocker.status != "resolved"]
        if unresolved:
            for blocker in unresolved:
                lines.append(
                    "- "
                    f"`{_text(blocker.severity)}` `{_text(blocker.id)}` "
                    f"on `{_text(blocker.task_id)}`: {_text(blocker.reason)}"
                )
        else:
            lines.append("- None.")
        lines.extend(["", "### Definition Of Done Evidence", ""])
        if run.dod_evidence:
            for gate in sorted(run.dod_evidence):
                lines.append(f"- {_text(gate)}: {_text(run.dod_evidence[gate])}")
        else:
            lines.append("- None recorded.")
        lines.append("")
    return "\n".join(lines)


def _backlog_document(runs: list[OrchestrationRun]) -> str:
    lines = [
        "# DGentic Orchestration Follow-Up Backlog",
        "",
        (
            "Generated by DGentic from orchestration blockers and follow-ups. "
            "Manual edits may be replaced."
        ),
        "",
        "## Open Follow-Ups",
        "",
    ]
    follow_up_count = 0
    for run, follow_up in _open_follow_ups(runs):
        follow_up_count += 1
        lines.append(
            "- "
            f"`{_text(run.id)}` / `{_text(follow_up.task_id)}` "
            f"-> {_text(follow_up.assigned_role)}: {_text(follow_up.description)}"
        )
    if follow_up_count == 0:
        lines.append("- None.")

    lines.extend(["", "## Unresolved Blockers", ""])
    blocker_count = 0
    for run, blocker in _unresolved_backlog_blockers(runs):
        blocker_count += 1
        lines.append(
            "- "
            f"`{_text(run.id)}` / `{_text(blocker.task_id)}` "
            f"`{_text(blocker.severity)}`: {_text(blocker.reason)}"
        )
    if blocker_count == 0:
        lines.append("- None.")
    lines.append("")
    return "\n".join(lines)


def _open_follow_ups(
    runs: list[OrchestrationRun],
) -> list[tuple[OrchestrationRun, OrchestrationFollowUp]]:
    return [
        (run, follow_up)
        for run in runs
        if run.status != PlanStatus.completed
        for follow_up in run.follow_ups
    ]


def _unresolved_backlog_blockers(
    runs: list[OrchestrationRun],
) -> list[tuple[OrchestrationRun, OrchestrationBlocker]]:
    return [
        (run, blocker)
        for run in runs
        if run.status != PlanStatus.completed
        for blocker in run.blockers
        if blocker.status != "resolved"
    ]


def _text(value: str) -> str:
    return redact_sensitive_values(value).replace("\r", " ").replace("\n", " ").strip()


def _csv(values: list[str]) -> str:
    if not values:
        return "none"
    return ", ".join(f"`{_text(value)}`" for value in values)
